volumes:
  datafiles:

services:
  db:
    image: mysql:8.0.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: servisdb
    volumes:
      - datafiles:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always

  servisapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: always
    environment:
      - ConnectionStrings__Default=server=db;port=3306;user=root;database=servisdb;password=password;SSL Mode=None
